name: CI for Building

on:
  push:
    branches:
      - main

jobs:
  checkout:
    steps:
      - name: Checkout source code

  test:
    steps:
      - name: Test with Pytest

  build:
    steps:
      - name: Build a container image