name: CI for Building

on:
  push:
    branches:
      - main

jobs:
  checkout:
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

  install:
    steps:
      - name: Setup virtual environment
        run: python3 -m venv .venv

      - name: Install Python dependencies
        run: ./venv/bin/pip3 install -r requirements.txt

  test:
    steps:
      - name: Perform tests with Pytest
        run: ./venv/bin/pytest